# Generated by Django 5.0.14 on 2026-03-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Подписчик Telegram',
                'verbose_name_plural': 'Подписчики Telegram',
            },
        ),
    ]
